saveFolder: ../campy_test/LE1_2/06282026
videoFilename: 0.mp4
frameRate: 40.0
recTimeInSec: 10000.0
infiniteRecording: true
numCams: 2
cameraSelection:
- 0
cameraNames:
- 1b
- 1c
cameraMake: basler
cameraSerialNo:
- '41927057'
- '41927063'
cameraSettings:
- ./configs/field_test/a2A1920-160umBAS_41927057_1b.pfs
- ./configs/field_test/a2A1920-160umBAS_41927063_1c.pfs
frameWidth: 1920
frameHeight: 1200
cameraTrigger: Line3
cameraOut: 3
cameraOutSource: ExposureActive
cameraDebug: true
grabTimeoutInMs: 1000
bufferSize: 500
gpuID:
- 0
- 0
ffmpegPath: C:/Users/Cornell/anaconda3/envs/campy/Library/bin/ffmpeg.exe
gpuMake: nvidia
preset: None
pixelFormatInput: gray
pixelFormatOutput: yuv420p
codec: h264
quality: 17
ffmpegLogLevel: warning
chunkLengthInSec: 5
displayFrameRate: 15.0
displayDownsample: 2
startArduino: false
startTriggerController: true
triggerController: pulsepal
waitForTriggerStart: true
pulsePalPythonPath: C:/Users/Cornell/Downloads/PulsePal-master/PulsePal-master/Python/Python3
pulsePalPort: COM4
pulsePalChannels:
- 1
- 2
pulseFrequencyHz: 40.0
pulseHighTimeSec: 0.005
pulseTrainDurationSec: 1800
pulsePalContinuous: true
pulsePalVoltage: 5
pulsePalRestingVoltage: 0
pulsePalTriggerChannel: 1
enableGPIOTimestampLogging: false
gpioSerialPort: COM6
gpioBaudRate: 119200
gpioLogFilename: gpio_log.csv
