saveFolder: D:/random_foraging/test/1c
videoFilename: 123.mp4
frameRate: 40
recTimeInSec: 10000
infiniteRecording: true
numCams: 1
cameraSelection: [0]
cameraNames: [1b]
cameraMake: basler
cameraSerialNo: ['41927057']
cameraSettings: ['C:/Users/Cornell/Desktop/Basler/campy_aya/configs/random_foraging_outdoor/a2A1920-160umBAS_41927057.pfs']
frameWidth: 1920
frameHeight: 1200
cameraTrigger: Line2
cameraOut: Line3
cameraOutSource: ExposureActive
cameraDebug: true
grabTimeoutInMs: 1000
bufferSize: 500
gpuID: [0]
ffmpegPath: auto
gpuMake: nvidia
preset: None
pixelFormatInput: gray
pixelFormatOutput: yuv420p
codec: h264
quality: 17
ffmpegLogLevel: warning
chunkLengthInSec: 5
displayFrameRate: 20
displayDownsample: 2
startArduino: false
startTriggerController: true
triggerController: pulsepal
waitForTriggerStart: true
pulsePalPythonPath: auto
pulsePalPort: COM8
pulsePalChannels: [1, 2]
pulseFrequencyHz: 40
pulseHighTimeSec: 0.005
pulseTrainDurationSec: 10000
pulsePalContinuous: true
pulsePalVoltage: 5
pulsePalRestingVoltage: 0
pulsePalTriggerChannel: 1
enableGPIOTimestampLogging: false
gpioSerialPort: COM5
gpioBaudRate: 119200
gpioLogFilename: gpio_log.csv
videoFolder: D:/random_foraging/test/1c
appendDateTimeSuffix: true
