# Four-camera W154 config with Pulse Pal software-started external trigger.
# Command:
#   campy-acquire ./configs/W153_WT/campy_config_W154_WT_pulsepal.yaml

# Recording parameters
saveFolder: "../campy_test/WT_training/W154_WT4/06232026_pm_WT6"
# saveFolder: "../campy_test/WT_training/W154_WT4/06192026_pm_WT2"
# saveFolder: "../campy_test/test/test/06162026_test"

videoFilename: "0.mp4"
frameRate: 40
recTimeInSec: 10000
infiniteRecording: True

# Camera parameters
numCams: 1
cameraSelection: [0]
cameraNames: ["Camera1"]
cameraMake: "basler"
cameraSerialNo: ["24188010"]
cameraSettings:
  - "./configs/W154_WT/acA1300-200uc_24188010.pfs"
frameWidth: 1280
frameHeight: 1024
cameraTrigger: "Line3"
cameraDebug: True
grabTimeoutInMs: 1000
bufferSize: 500

# Compression parameters
gpuID: [0]
ffmpegPath: "C:/Users/Cornell/anaconda3/envs/campy/Library/bin/ffmpeg.exe"
gpuMake: "nvidia"
preset: "None"
pixelFormatInput: "gray"
pixelFormatOutput: "yuv420p"
codec: "h264"
quality: 17
ffmpegLogLevel: "warning"

# Display parameters
chunkLengthInSec: 5
displayFrameRate: 15
displayDownsample: 2

# Trigger parameters
startArduino: False
startTriggerController: True
triggerController: "pulsepal"
waitForTriggerStart: True

# Pulse Pal parameters
pulsePalPythonPath: "C:/Users/Cornell/Downloads/PulsePal-master/PulsePal-master/Python/Python3"
pulsePalPort: "COM10"
pulsePalChannels: [1]
pulseFrequencyHz: 40
pulseHighTimeSec: 0.005
pulseTrainDurationSec: 1800
pulsePalContinuous: True
pulsePalVoltage: 5
pulsePalRestingVoltage: 0
pulsePalTriggerChannel: 1
